import type { Tone } from './depth';

// Curated, tone-appropriate vocabulary. Content is generated by recombining
// these banks with a seeded RNG (see feedGenerator.ts / portalTemplates.ts),
// so output is varied but never reads as noise — every combination was
// written to make sense together within its tone.

export const ADJECTIVES: Record<Tone, string[]> = {
  light: [
    'sunlit', 'bouncy', 'citrus', 'friendly', 'glittering', 'warm', 'candy-colored',
    'buoyant', 'cheerful', 'fizzy', 'golden', 'playful', 'breezy', 'sparkling', 'cozy',
  ],
  mid: [
    'muted', 'hushed', 'weathered', 'liminal', 'grey-lit', 'half-remembered', 'drifting',
    'quiet', 'unfinished', 'foggy', 'in-between', 'thinning', 'faded', 'wandering', 'still',
  ],
  deep: [
    'hollow', 'silent', 'unlit', 'cracked', 'crimson-veined', 'ash-covered', 'forgotten',
    'breathing', 'watching', 'submerged', 'ancient', 'threadbare', 'bone-pale', 'coiled', 'waiting',
  ],
};

export const NOUNS: Record<Tone, string[]> = {
  light: [
    'lemonade stand', 'paper airplane', 'balloon', 'bicycle bell', 'sticker sheet', 'sandcastle',
    'kite string', 'jukebox', 'porch light', 'ice cream truck', 'birthday candle', 'hopscotch square',
  ],
  mid: [
    'payphone', 'waiting room', 'vending machine', 'elevator', 'parking garage', 'hallway',
    'radio static', 'bus stop', 'motel sign', 'stairwell', 'departure board', 'answering machine',
  ],
  deep: [
    'well', 'attic', 'mirror', 'basement door', 'tunnel', 'grandfather clock', 'letterbox',
    'cellar', 'lighthouse', 'crypt', 'switchboard', 'flooded room', 'birdcage', 'reflection',
  ],
};

export const WHISPER_LINES: Record<Tone, string[]> = {
  light: [
    "Someone, somewhere, just laughed for no reason. That was probably good.",
    'This spot smells like sunscreen and cut grass, if spots could smell like things.',
    "You've scrolled past 100% of the people who gave up before you did today.",
    'A tiny confetti cannon just went off two scrolls ago. You missed it. There will be more.',
    'Fun fact: nobody knows why this feed exists. That is part of the appeal.',
    'If this were a song it would have a kazoo solo.',
    'Somewhere a dog is very happy about a stick.',
    "This is your reminder that you're doing great, probably.",
    'The color of this card was chosen just for you and will never be shown this way again.',
    'A very small parade is passing through this pixel.',
    'Keep scrolling. It gets weirder before it gets better, and better before it gets weird again.',
    'This message was left here by someone who scrolled this far and smiled.',
    'Somewhere below, things start to change. You will not notice exactly when.',
    'The lemonade is free but the wifi password is a secret.',
    'You are currently the only person seeing exactly this. Neat, right?',
  ],
  mid: [
    'The hallway keeps going. Nobody has measured how far.',
    'You start to notice the quiet between the fun parts.',
    'Somewhere a payphone rings twice and stops.',
    'This far down, the colors remember being brighter.',
    'A lot of people turn back around here. You are still here.',
    'The static in the background used to be a song.',
    'Time moves normally here, which somehow feels unusual.',
    'Nobody official confirmed this feed is safe. Nobody official confirmed anything.',
    'You could stop scrolling. You could also see what is next.',
    'Something about this depth makes people type slower in the comments.',
    'The light is thinner here, like it is being rationed.',
    'A door somewhere just closed on its own. Probably the wind.',
    'This is the part of the trip nobody warns you about — not scary, just different.',
    'The feed has started repeating a shape you have not noticed yet.',
  ],
  deep: [
    'It is very quiet down here. That is not a complaint.',
    'Something has been counting your scrolls. It is not unfriendly. It is just counting.',
    'The comments get shorter this deep. People choose their words carefully.',
    'You are further than most people go. Most people do not come back to check.',
    'The walls of the feed are thinner here — you can almost see the code.',
    'A low hum has been present for a while. You may not have noticed when it started.',
    'This far down, nothing new happens quickly. Everything happens eventually.',
    'Somebody left a light on for you. It is very small.',
    'The shapes down here remember being something else.',
    'This message has been read by fewer people than you would think.',
    'It is not that it is dangerous. It is that it is honest.',
    'You have been scrolling long enough that this has become a kind of home.',
    'Whatever is down here has been very patient.',
    'There is a bottom. Nobody has told anyone what is there.',
  ],
};

export const PORTAL_ACTIONS: Record<Tone, string[]> = {
  light: ['Open', 'Poke', 'Peek into', 'Unwrap', 'Bounce into', 'Say hi to'],
  mid: ['Step into', 'Listen to', 'Follow', 'Approach', 'Wait near', 'Read'],
  deep: ['Enter', 'Descend into', 'Face', 'Answer', 'Sit with', 'Open, carefully,'],
};

export function titleFor(tone: Tone, rng: () => number): string {
  const action = PORTAL_ACTIONS[tone][Math.floor(rng() * PORTAL_ACTIONS[tone].length)];
  const adj = ADJECTIVES[tone][Math.floor(rng() * ADJECTIVES[tone].length)];
  const noun = NOUNS[tone][Math.floor(rng() * NOUNS[tone].length)];
  return `${action} the ${adj} ${noun}`;
}

const BLURB_TEMPLATES: Record<Tone, ((adj: string, noun: string) => string)[]> = {
  light: [
    (adj, noun) => `A ${adj} ${noun} appeared out of nowhere. It's giving off great energy.`,
    (adj, noun) => `Someone left a ${adj} ${noun} here for whoever scrolled far enough.`,
    (adj, noun) => `This ${noun} is extremely ${adj} and wants to be clicked.`,
  ],
  mid: [
    (adj, noun) => `There's a ${adj} ${noun} here. Nobody's sure how long it's been.`,
    (adj, noun) => `A ${noun}, ${adj} and unattended. It might be worth a look.`,
    (adj, noun) => `You keep passing ${adj} ${noun}s like this. This one feels different.`,
  ],
  deep: [
    (adj, noun) => `A ${adj} ${noun} waits here. It has been waiting for a while.`,
    (adj, noun) => `This ${noun} is ${adj}. It knows you're reading this.`,
    (adj, noun) => `Something about this ${noun} is ${adj} in a way that's hard to name.`,
  ],
};

export function blurbFor(tone: Tone, rng: () => number): string {
  const adj = ADJECTIVES[tone][Math.floor(rng() * ADJECTIVES[tone].length)];
  const noun = NOUNS[tone][Math.floor(rng() * NOUNS[tone].length)];
  const template = BLURB_TEMPLATES[tone][Math.floor(rng() * BLURB_TEMPLATES[tone].length)];
  return template(adj, noun);
}

export function whisperFor(tone: Tone, rng: () => number): string {
  const lines = WHISPER_LINES[tone];
  return lines[Math.floor(rng() * lines.length)];
}
